name: youth_job_policy_app
description: 청년 일자리 정책 평가 및 추천 앱

# 앱 버전 및 빌드 번호
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI 관련 패키지
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0

  # 상태 관리 패키지
  provider: ^6.1.1

  # 네트워크 및 데이터 처리 패키지
  http: ^1.1.2
  csv: ^5.1.1
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2

  # Firebase 패키지
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6

  # 위치 및 지도 관련 패키지
  # google_maps_flutter: ^2.5.0
  # geolocator: ^9.0.2

  # 유틸리티 패키지
  intl: ^0.19.0
  permission_handler: ^11.1.0
  url_launcher: ^6.2.2
  file_picker: ^6.1.1
  image_picker: ^1.0.4
  flutter_local_notifications: ^14.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Regular.ttf
        - asset: assets/fonts/NotoSansKR-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansKR-Bold.ttf
          weight: 700